NegativeTime = -1
ConditionNotSatisfied = -2
NoWorkerExists = -3
WrongBuildingName = -4
WrongUpgradeName = -5
WrongUnitName = -6
UnknownError = -7
WrongFlag = -8
SupplyBlocked = -9
NoBarrackExists = -10
NoOneGathersGasOrMineral = -11
MineralFieldsAreFull = -12
NoOneGathersGas = -13
GasLayersAreFull = -14
NotEnoughWorkers = -15
NoRefineryExists = -16
ChronoCooldown = -17
ChronoNotAvailable = -18
AlreadyBoosted = -19 
UnboostableBuilding = -20
WrongIndex = -21
NoItemToDelete = -22
NoPathExists = -23
NotUnitType = -24
NotBuildingType = -25
UniqueOnly = -26
WrongRace = -27
WrongFileFormat = -28
IncompatibleVersion = -29
CannotBuildLarva = -30
NotEnoughEnergy = -31

def ErrorMsg(e):
    if e == NegativeTime:
        return "Wrong time - negative number was inserted"
    elif e == ConditionNotSatisfied:
        return "Prerequisite building does not exist"
    elif e == NoWorkerExists:
        return "No worker exists"
    elif e == WrongBuildingName:
        return "Wrong building name"
    elif e == WrongUpgradeName:
        return "Wrong upgrade name"
    elif e == WrongUnitName:
        return "Wrong unit name"
    elif e == UnknownError:
        return "Unknown error"
    elif e == WrongFlag:
        return "Wrong type - it must be 'unit', 'building' or 'upgrade'"
    elif e == SupplyBlocked:
        return "Supply blocked - you should construct more supply"
    elif e == NoBarrackExists:
        return "No appropriate production facility exists"
    elif e == NoOneGathersGasOrMineral:
        return "No one gathers gas or mineral"
    elif e == MineralFieldsAreFull:
        return "Mineral fields are full"
    elif e == NoOneGathersGas:
        return "No one gathers gas"
    elif e == GasLayersAreFull:
        return "Gas geysers are full"
    elif e == NotEnoughWorkers:
        return "Not enough workers"
    elif e == NoRefineryExists:
        return "No refinery exists"
    elif e == ChronoCooldown:
        return "Chronoboost in cooldown. Removing latest chronoboost from queue."
    elif e == ChronoNotAvailable:
        return "Chronoboost is not available. Removing latest chronoboost from queue."
    elif e == AlreadyBoosted:
        return "All buildings are already boosted. Removing latest chronoboost from queue."
    elif e == UnboostableBuilding:
        return "That building isn't able to be chronoboosted"
    elif e == WrongIndex:
        return "Wrong index"
    elif e== NoItemToDelete:
        return "No item to delete"
    elif e == NoPathExists:
        return "No Icon Exists"
    elif e == NotUnitType:
        return "Not unit type"
    elif e == NotBuildingType:
        return "Not building type"
    elif e == UniqueOnly:
        return "You can't do this more than once"
    elif e == WrongRace:
        return "Wrong race name"
    elif e == WrongFileFormat:
        return "Wrong file format or it's cracked"
    elif e == IncompatibleVersion:
        return "Incompatible version file"
    elif e == CannotBuildLarva:
        return "Cannot build larva. They are generated by a hatchery."
    elif e == NotEnoughEnergy:
        return "Not enough energy."
    else:
        return "Unknown error code"
